---
# tasks file for apache_web
- name: Install apache
  ansible.builtin.dnf:
    name: "{{ apache_package }}"
    state: latest

- name: Start and enable apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    enabled: true

- name: Deploy the web page
  ansible.builtin.copy:
    content: "Welcome to roles/n"
    dest: "{{web_root }}/{{ index_file }}"
    mode: '0644'

- name: Open HTTP port in firewall
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: Restart Apache
