---
- name: play to demonstarte a variable usage
  hosts: serverd
  #vars:
   # pkg: httpd
  tasks:
    - name: Task to dispaly a message
      ansible.builtin.debug:
        msg: "The value of the variable pkg is: {{pkg}}"
